### ISSUE TITLE
No alerts

### ISSUE THREAD

**Issue by GWspekulatius** [raiguard/Factorio-LtnManager#123]
#### Describe the Bug

When LTN gives a timeout warning like "train removed after ... ticks", no entry is present in the alerts tab of LTN manager. This used to work in previous versions.

Currently using:
LTN 1.14.6
LTN Manager 0.3.7

In mod settings i have set LTN message level to 1: errors & warnings.

#### To Reproduce

In LTN mod settings reduce the delivery timeout to the smallest value: 60 seconds. Wait for a train to get dispatched. LTN will create a timeout alert if train has not returned to depot within 60 seconds.

**Comment by raiguard** [comment]
I just tested it and it's working fine for me:

![image](https://user-images.githubusercontent.com/3515394/96804516-74470680-13cc-11eb-906d-c22cad2beb5e.png)

If you are still having this problem, please upload your save file and I'll take a look.

**Comment by Dominiquini** [comment]
Sometimes I received alerts from LTN about missing trains on the depot; failed to delivery some cargo or wrong cargo arriving in some requester stations, but none of these appear in the "Alerts" tab of the LTN Manager!

**Comment by raiguard** [comment]
It can take a while for the alerts tab to update, since it won't update until the next LTN data cycle. While LTN will show the alert notification immediately, LTNM won't show it immediately. I tested the alerts system earlier today after someone gave a similar report on discord, and it is working perfectly.

**Comment by Dominiquini** [comment]
I just did a test here where I put a station and ordered an item, but I didn't unload the train. After 120s stopped at the requester station, the train returns to the Depot, fully loaded and an LTN alert appears next to the Shortcut Bar, but nothing in the LTN Manager GUI! I waited several minutes and nothing appeared there!
If you want to check this, I can attach here my save game, but it is heavily modded!

Thanks.

**Comment by raiguard** [comment]
Yes, please attach your save game.

**Comment by Dominiquini** [comment]
Save Game: (Same file uploaded in two different hosting services)
- https://www.mediafire.com/file/eqciu8xjywbefdn/Barbatron.zip/file
- https://ufile.io/9kqryx71

* I was unable to attach the file here because it is too big!

If you need more things, like the entire profile folder with my mods and settings, let me know!

Thanks.

**Comment by raiguard** [comment]
Aha! Turns out there _is_ a bug here after all. When you click "delete all alerts", the flag to delete all alerts never got reset, so any alerts you get from that point on would never show up.

This is why save files are important. Thank you!

**Comment by Dominiquini** [comment]
I must thank you! This is an amazing mod!

**Comment by GWspekulatius** [comment]
Im glad you could resolve this without my help. I can remember pressing the 'delete all alerts' button. So this was probably the reason it was not working for me also.
