### ISSUE TITLE
[0.3.10] Double search bar

### ISSUE THREAD

**Issue by SpeckledFleebeedoo** [raiguard/Factorio-LtnManager#134]
#### Describe the Bug

The search bar appears twice, one of them is inoperative.

#### To Reproduce

No idea. I recently changed all the stations on the right base to be in network 2 instead of in -1, and the issue popped up afterwards. It persistently appears in this save file.

#### Save file & Username

[Save file](https://drive.google.com/file/d/1z7T4M_FI7esSOvzyKaxJ_QG3z1NyyoFC/view?usp=sharing)

Username: SpeckledFleebeedoo

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5626755/factorio-current.log)

**Comment by raiguard** [comment]
As per our discussion on [Discord](https://discordapp.com/channels/139677590393716737/139677590393716737/783530299287404545), I'm putting this into the category of "won't fix" because it won't be a problem in the next major version anyway. To fix the issue, go to the history tab and click search. :)
