### ISSUE TITLE
Manager Crash when accessing Stations tab

### ISSUE THREAD

**Issue by Warringer** [raiguard/Factorio-LtnManager#137]
I just encountered this error message, when I tried to access the Station tab. 

```
The mod LTN Manager [ALPHA] (0.3.10) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/scripts/gui/main-tabs/stations.lua:217: attempt to get length of local 'signals' (a nil value)
stack traceback:
	__LtnManager__/scripts/gui/main-tabs/stations.lua:217: in function 'update'
	__LtnManager__/scripts/gui/main.lua:394: in function 'update'
	__LtnManager__/scripts/gui/main.lua:421: in function 'update_active_tab'
	__LtnManager__/scripts/gui/main.lua:64: in function 'handler'
	__flib__/gui.lua:389: in function <__flib__/gui.lua:375>
```

The tab did work correctly for me for a while, but after a few uses it didn't work out anymore.

**Comment by crazybmanp** [comment]
Gonna attach my feeback here because it may be related. i noticed a very similar if not same crash after changing a stop name, while an active delivery was running. it seems like it could be an issue with accessing a stop by an old name and finding no stop? To know if these issues are related; did you rename a stop before this crash?

**Comment by raiguard** [comment]
I'm 99% certain this will be handled in the GUI rewrite, so I'm closing this for now.
