### ISSUE TITLE
Can't find main locomotive

### ISSUE THREAD

**Issue by Grimshad** [raiguard/Factorio-LtnManager#168]
#### Describe the Bug

I had a 5 unit train: locomotive, fluid, cargo, cargo, cargo
Biters destroyed the 4th unit, then LTN manager crashed I assume because the 5th unit (cargo) no longer had a locomotive associated with it.

#### Log file

The mod LTN Manager (0.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:760: attempt to index field 'main_locomotive' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:760: in function '?'
	__LtnManager__/scripts/ltn-data.lua:1074: in function 'iterate'
	__LtnManager__/control.lua:175: in function <__LtnManager__/control.lua:160>

**Comment by vanseverk** [comment]
**Describe the bug**
I saw a train with one locomotive and two fluids which was unable to load water as one fluid had oil, the other had sulfuric acid. [Loco]-[Sulfuric Acid]-[Oil] Because they weren't supposed to, I deleted the wagon with sulfuric acid, which causd the crash. After loading and trying again, I was unable to reproduce this.

**Log file**
The mod LTN Manager (0.4.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:419: attempt to index field 'main_locomotive' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:419: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1076: in function 'iterate'
	__LtnManager__/control.lua:165: in function <__LtnManager__/control.lua:150>
