### ISSUE TITLE
Crash ~2sec after loading game

### ISSUE THREAD

**Issue by Sakreton** [raiguard/Factorio-LtnManager#29]
Hey, first of all thank you very much for developing this mod!
After i installed LTNM and loaded up my savegame, a few seconds after i am ingame i get this crash:

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/util.lua:71: attempt to concatenate field 'from' (a nil value)
stack traceback:
	__LtnManager__/scripts/util.lua:71: in function 'get_status_string'
	__LtnManager__/scripts/data-manager.lua:210: in function 'sort_depot_trains'
	__LtnManager__/scripts/data-manager.lua:416: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

I attached the log file, if you need any further information like a savegame in could send that to.

Thank you! 

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4465453/factorio-current.log)

**Comment by raiguard** [comment]
Can you please send me your save game?

**Comment by Sakreton** [comment]
oh well, sorry xD 

Save file to big for github.
I used some other mods to but they dont seem to be the problem.
I just tried to load it up again same error but now not as fast as before ~10-20secs.

https://drive.google.com/file/d/1cWdGJLqIsxuC3Bu7wu2xsuopLwIAjD7I/view?usp=sharing

Sorry for the inconvenience :)

**Comment by raiguard** [comment]
It's no problem. Thank you, I'll see what I can find!

**Comment by raiguard** [comment]
This is quite odd... quite odd indeed. I fixed the first bug, which was that the function that generates the train's status string that you see on the depots list was using the train's current status instead of the status that was stored during data iteration.

But then it crashed again in the same place, because somehow the same information was missing. So for now, I added a check that will just display "N/A" if that ever happens, so it won't crash anymore.

Thank you for the report, I'll release a patch shortly!
