### ISSUE TITLE
Search in the inventory tab

### ISSUE THREAD

**Issue by therock182** [raiguard/Factorio-LtnManager#32]
i can search for "ore" and i get all ores in my ltn. if i search for "copper or iron" i get nothing as result.
same for "plate" where i get results and if i search for "steel or copper and so on" i get nothing as result.
i can search for "circuit" but not for "advanced or electronic".

it seems its always the first word in the itemname where i dont get a result. the second and third word i get results. for example i can search "science" or "pack" but not "automation".

a item with only one word i cant search for, like "inserter".

**Comment by jarquafelmu** [comment]
If you are referring to the character inventory then this mod doesn't affect that. This mod only adds the LTN manager. 

That being said, I do know what is happening here. The search looks for items that contain the word that you type in. If you type "ore" then both "Iron _ore_" and "Copper _ore_" would show up because they both contain ore. However no single item contains the the search "iron and copper ore".

If it did the item would have to be named "Iron and Copper _ore" or something like that. Some searches let you use wildcards which tells the searcher to treat certain things special but most are just a literal 'search-the-name-for-the-word'.

I hope that helps!

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next release.
