### ISSUE TITLE
About Alert

### ISSUE THREAD

**Issue by dairen** [raiguard/Factorio-LtnManager#36]
i'm new with LTN; i set up some config and that seems work

with you'r manager :) i see a lot of alert; incomplete delivery or incorrect pickup

i have some trains with two or more items in wagon

maybe if you know LTN, the alert can to explain how to do to remove herself :)

**Comment by raiguard** [comment]
If I understand correctly, you want me to add explanations for how to resolve an incomplete pickup Sorry, but that's not feasible because of the wide variety of reasons why it could be happening. The purpose of the alerts system is not to tell you _how_ to fix an issue, it's to let you know that there is an issue in the first place.

If you need help configuring your LTN setup, post a thread on the [LTN subforum](https://forums.factorio.com/viewforum.php?f=214).
