### ISSUE TITLE
Scroll station list to start of providers/requestors/in transit

### ISSUE THREAD

**Issue by danyax** [raiguard/Factorio-LtnManager#50]
Inventory tab - when clicking on provider (green), requestor (orange) or transit (blue) items scroll right pane to start of corresponding station types. Help a lot in you have dozens of stations for one material

**Comment by raiguard** [comment]
Thanks for the suggestion! I'll add it to my list.

**Comment by raiguard** [comment]
So, this is no longer going to be applicable because the new inventory tab won't even have the view material locations functionality. Instead, you achieve that behavior by searching for the material you want on the stations tab. This accomplishes the same thing while letting you sort the list how you want, and see all of the info for that station at once.

![image](https://user-images.githubusercontent.com/3515394/95821426-1c7f1000-0ce7-11eb-8fe5-d9859f96a727.png)
