### ISSUE TITLE
View inconsistencies

### ISSUE THREAD

**Issue by JanEggers** [raiguard/Factorio-LtnManager#57]
**Describe the bug**
The ui shows a requested amount of something. but the requesting station is not listed. or the amounts dont match. it seems the higher the throughput the more likely the issue ocurrs, or maybe a general refresh issue that the right side takes data from the moment a selection has been done on the left side while the left side still shows the data from a snapshot when the ui was opened up.

**Save file**
![image](https://user-images.githubusercontent.com/6747376/80119813-7994d700-858a-11ea-9b92-f99309c68193.png)

![image](https://user-images.githubusercontent.com/6747376/80120234-fb850000-858a-11ea-936c-71364000e49d.png)

![image](https://user-images.githubusercontent.com/6747376/80120780-c9c06900-858b-11ea-8e7d-99e1128a4823.png)

**Comment by JanEggers** [comment]
https://drive.google.com/open?id=1L42cg_jdb2rxNEPMCVTydmAM-wWMnA3-

the save

**Comment by raiguard** [comment]
This is happening because when you click an inventory button, only the right side of the GUI is updated. Turns out that I cache those total numbers when assembling the left side, so those numbers will match what's on the left side.

The fix is simply to refresh the entire page when you click a button. It'll be in for the next version.

**Comment by JanEggers** [comment]
thx
