### ISSUE TITLE
Handling lots of warnings.

### ISSUE THREAD

**Issue by bc-lee** [raiguard/Factorio-LtnManager#60]
**Is your feature request related to a problem? Please describe.**
I have a little bit awkward LTN network which doesn't empty items on the request station. This network generate lots of warnings, so I'd like to cleanup them easily.
If I have lots of warnings(say, 100+) then the GUI of LTN Managers is extremely slow, so it is not feasible to remove them one by one. 

**Describe the solution you'd like**
- Add a button to clear all alerts.
- Use Lua`s pattern matching to ignore specific patterns of warnings.

**Additional context**

**Comment by jpetrihst** [comment]
This is important because if there are a lot of alerts (more than 100, I guess), the load on the server and the clients increases considerably. And, if you then try to delete a message, the game 'hangs' for a couple of seconds (1-3). It is not possible to delete a significant number of error messages under these circumstances.
Current solution: Stop the server, remove LTN Manager mod, start server, stop server, re-add mod, start server and the messages are gone.
After that the load on the server is back to about 0.3 (from above 1) and the in-game fps are at stable 60 (before drops to 15 where "normal"). Also, deleting new messages does not have an impact on game performance, as long as the message queue is relatively empty.
The server is a virtual machine running linux with 4 cores (Xeon Gold 6136 based), 16 GB RAM and SSD disk, so the problems should not be due to weak hardware.

**Comment by raiguard** [comment]
Hey, sorry for the delay, I'm horrible at juggling projects and have been otherwise occupied.

The main issue causing all of the slowdown is that I neglected to put a limit on the number of alerts it stores at a time. I didn't realize that some maps might have tons and tons of alerts. So I will also fix that for the next version.

I will merge your PRs later today. However, I won't be able to release a new version today, because the current state of master is not suitable for public consumption, and there is a lot of work to be done to re-add some missing features, specifically the search GUI.

**Comment by raiguard** [comment]
This was implemented in v0.4, with a "clear all alerts" button and advanced search on all tabs.
