### ISSUE TITLE
Better handling of multiple train networks

### ISSUE THREAD

**Issue by mtomsovic** [raiguard/Factorio-LtnManager#86]
#### Is your feature request related to a problem? Please describe.

Trying to use search to filter Depots, Stations, Inventory, etc based on Network ID does not seem to work.  Entering a specific Network ID does not limit the results to only that network.

#### Describe the solution you'd like

I think it'd be great if there could be a drop-down menu in the UI that has the Network IDs in use.  This drop-down would be in the same spot across all LTN Manager tabs and the chosen ID will be used in the UI globally until changed again showing only items from that Network ID on whatever tab is opened.  An "All" option would be default, then you could choose -1 or -2 (or whatever Network IDs are in use) and then that new chosen network ID is saved and used between UI close/open until changed again, or until an exit/re-load of the game.

Having the Network ID displayed in the UI when listing (or maybe hovering) stations/inventory->stations/history/etc will be very helpful when viewing the All networks option.

**Comment by raiguard** [comment]
The network ID input field is the encoded binary ID, it's not an integer. So, typing 6 won't actually show network 6, it will show networks 4 and 2. This is how LTN itself works as well.

I do plan on adding an LTN combinator-esque network picker at some point, once I improve performance and fix some glaring GUI logic issues.

**Comment by dbiser99** [comment]
I think this falls under the same "issue"...even more basic than searching the network ID's I would love to just see them listed somewhere. I see 3 potential primary locations.

1. Add it to the Depot list so the Depots show the depot stats as well as which network they belong to.
2. Technically there under Control Signals, but do the same for the Station List so it stands out more.
3, This is the one I'm most interested in: If I have done things correctly, each depot is its own network, so arguably redundant, but it is a different way to view the data....make a Network tab that lists the used networks ideally with the ability to add a descriptive label and optionally view all the stations and depots associated with it (just a list...the station and depot tabs can be used for detail.) Thinking something possibly similar to the Networks tab in Advanced Logistic System Fork

Great work otherwise. Been using LTN for awhile but recently started expanding my use. Started to get harder to keep track of everything across the base and I had seen this and thought I'd check it out. Just started using it, but so far haven't run into any bugs, and it's been nice to be able to get the full system picture. Looking forward to the progression to a "final" mod version.

**Comment by Yousei9** [comment]
Considering how much network id matters for larger bases I would move it out of control signals into its own column right next to station status as plain, easily readable number. Optionally showing it hex value would be fancy.

For depots network id could be below the status line.

**Comment by raiguard** [comment]
The network ID used to actually be displayed in its own column, but I removed it because long numbers would get cut off.

I will be considering solutions for this in v0.4, which will involve a complete GUI rewrite to get rid of the mountain of technical debt it has accrued.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/95007502-f3b39800-05cd-11eb-82bd-72479162f4e8.png)

So, I am working on the GUI rewrite. Search is now global across all tabs and persists across open/close. Right now, the network ID is still a plain input box, but I plan on making a pop-up GUI that will allow you to select specific networks to show/hide. If I do depot descriptions, I'll put them in that pop-up so you can view them while deciding which networks to show.

For now, I have added the network ID to each depot's button on the depots tab. I will also be adding the network ID to every object I can think of where it would be useful (stations, history, alerts, etc).

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/95669926-d4bf8380-0b42-11eb-85e6-e45568c647e5.png)
The new stations tab has the network ID as a column again. Additionally, the text search will match against whichever column you're currently sorting by. So you can search network IDs by selecting that column's title, then typing in the search box. :D

**Comment by Yousei9** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/3515394/95669926-d4bf8380-0b42-11eb-85e6-e45568c647e5.png)
> The new stations tab has the network ID as a column again. Additionally, the text search will match against whichever column you're currently sorting by. So you can search network IDs by selecting that column's title, then typing in the search box. :D
A fun feature from a technical point, but it seems counter intuitive allowing ID search in search field when there's a dedicated ID search field. 
Without reading this I certainly would have wondered why search doesn't return "Coal Mine 2" in Network 1 when searching for "2" while having sorted by ID.

Additionally, how would search behave if ID is set to 1 and you search for 2?

**Comment by raiguard** [comment]
> A fun feature from a technical point, but it seems counter intuitive allowing ID search in search field when there's a dedicated ID search field.

Dafuq, somehow I managed to forget that that existed... wow.

> To me the expected behavior of the search field would be to search in station name, provided/requested and shipments regardless of which column is sorted by.

After talking to you on Discord, you're right. This search implementation is completely borked. Time to do it again! :(

**Comment by raiguard** [comment]
This was done in v0.4.
