### ISSUE TITLE
[0.2.3] Crash when trying to open GUI

### ISSUE THREAD

**Issue by skofisk** [raiguard/Factorio-LtnManager#92]
#### Describe the Bug

Mod crashes when trying to open gui, error on LTN shortcut button, or clicking alert box.

```
The mod LTN Manager [ALPHA] (0.2.3) caused a non-recoverable error.
Error while running event LtnManager::on_gui_click (ID 1)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	__LtnManager__/scripts/gui/main.lua:307: in function 'update'
	__LtnManager__/scripts/gui/alert-popup.lua:17: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>
stack traceback:
	[C]: in function '__newindex'
	__LtnManager__/scripts/gui/main.lua:307: in function 'update'
	__LtnManager__/scripts/gui/alert-popup.lua:17: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>
```
#### To Reproduce

1. Load save, click LTN shortcut or alert box

#### Save file & Username

username: Skofisk
[PyAL-LTNM-crash.zip](https://github.com/raiguard/Factorio-LtnManager/files/4809894/PyAL-LTN-crash.zip)

#### Log file
Multiple crashes in this logfile, both from button and alert box
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4809897/factorio-current.log)

**Comment by dennisahlin** [comment]
I guess same issue but when pressing GUI button instead of alert:
```
The mod LTN Manager [ALPHA] (0.2.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_lua_shortcut (ID 34)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	__LtnManager__/scripts/gui/main-tabs/alerts.lua:78: in function 'update'
	__LtnManager__/scripts/gui/main.lua:328: in function 'update'
	__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
	__LtnManager__/scripts/gui/main.lua:360: in function 'open'
	__LtnManager__/scripts/gui/main.lua:390: in function 'toggle'
	__LtnManager__/control.lua:138: in function <__LtnManager__/control.lua:133>
stack traceback:
	[C]: in function '__index'
	__LtnManager__/scripts/gui/main-tabs/alerts.lua:78: in function 'update'
	__LtnManager__/scripts/gui/main.lua:328: in function 'update'
	__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
	__LtnManager__/scripts/gui/main.lua:360: in function 'open'
	__LtnManager__/scripts/gui/main.lua:390: in function 'toggle'
	__LtnManager__/control.lua:138: in function <__LtnManager__/control.lua:133>
```

**Comment by raiguard** [comment]
So, I have no idea how this could have happened. Somehow the GUI was destroyed, but the data for it still exists in the player's data table. Can you remember what you were doing prior to experiencing the crash for the first time?

Changing any mods in your save file, whether adding, removing, or updating, should fix this crash. I'll release a patch tonight that will let you fix this with the `/LtnManager refresh-player-data` command, should this happen again. Unfortunately I can't fix the actual issue because I don't yet know what causes it!

If anyone else experiences this crash, please try to go back to an autosave where it doesn't happen, then try to figure out how it happened. My only theory so far is that some other mod destroyed the GUI without asking first.

**Comment by raiguard** [comment]
So, the only way I can think of this happening is for another mod to go in and tamper with my GUI. I'll add measures to detect if the GUI has been invalidated, and recreate it if so. I'll have the patch out either tonight or tomorrow night.

**Comment by dennisahlin** [comment]
Sorry, can't think of anything specific I did before this occured :(

**Comment by skofisk** [comment]
The bug was in the pyanodon modpack, just fixed https://github.com/pyanodon/pycoalprocessing/commit/780512d5d9b6bb3d7ba89ab9855b27305721bb25
Got the "invalid gui, recreating" message before update to latest pycoalprocessing

**Comment by raiguard** [comment]
So, funny story, I actually discovered that PyCoalProcessing was at fault yesterday, completely by accident. Turns out that closing the mod's "wiki" GUI destroys anything in `screen`, including LTNM and Recipe Book. I contacted the one who is currently maintaining the PySuite and he is putting out a fix.
